### ISSUE TITLE
MULTI_STAGE_MEANFIELD error

### ISSUE THREAD

**Issue by baoqiangcao** [martinkersner/train-CRF-RNN#18]
I have been trying to fix this for a while and it would be great if you could help.

I have the caffe version from bittnt installed and the followed all the steps to generate all the data files and then when I ran solve.py, I got such error:
ython solve.py 2
WARNING: Logging before InitGoogleLogging() is written to STDERR
I0527 03:05:20.191397 17587 solver.cpp:54] Initializing solver from parameters: 
test_iter: 261
test_interval: 1333
base_lr: 1e-13
display: 50
max_iter: 100000
lr_policy: "fixed"
momentum: 0.99
weight_decay: 0.0005
snapshot: 1000
snapshot_prefix: "models/train"
solver_mode: GPU
net: "TVG_CRFRNN_COCO_VOC_TRAIN_3_CLASSES.prototxt"
test_initialization: false
I0527 03:05:20.191462 17587 solver.cpp:96] Creating training net from net file: TVG_CRFRNN_COCO_VOC_TRAIN_3_CLASSES.prototxt
[libprotobuf ERROR google/protobuf/text_format.cc:245] Error parsing text-format caffe.NetParameter: 3:8: Message type "caffe.NetParameter" has no field named "Layers".
F0527 03:05:20.191532 17587 upgrade_proto.cpp:932] Check failed: ReadProtoFromTextFile(param_file, param) Failed to parse NetParameter file: TVG_CRFRNN_COCO_VOC_TRAIN_3_CLASSES.prototxt
*** Check failure stack trace: ***
Aborted

Some people said it is becuase the prototxt file compatibility issue, such as, "layers"  and "CONVOLUTION"  in the prototxt file should be changed to "Layers/layer" and "Convolution". I did it but no luck still.

Any help on fixing it?

**Comment by martinkersner** [comment]
Hi @baoqiangcao,

Yes, this problem is related to compatibility issues between caffe versions. If you have recently downloaded caffe version from bittnt you might have downloaded their new version with is integrated with the latest caffe future version. The renaming should solve your problem. For those field names that cause problems, try to search in new [prototxt file](https://github.com/torrvision/crfasrnn/blob/master/python-scripts/TVG_CRFRNN_new_deploy.prototxt) and correct field names in your definition file accordingly.

Cheers,

Martin
