### ISSUE TITLE
GPU memory for training 

### ISSUE THREAD

**Issue by sankar19** [martinkersner/train-CRF-RNN#3]
How much gpu memory (batch size, spatial dimensions) was required when you trained crfasrnn? I tried to train images of 500x500 dimensions of batch size 1 on 4gb card - there was an error of out of memory. I am going to try reducing the dimensions.

Thanks,
Sankar

**Comment by martinkersner** [comment]
When training with 21 classes, image dimensions 500x500 and batch size 1, training requires about 7 GB of RAM.

**Comment by charterscruz** [comment]
Hi,

Do you think that training might be performed using [fcn8's](https://gist.github.com/longjon/1bf3aa1e0b8e788d7e1d) using a GPU with only 4 GB?
I know that the performance might be worst but to play around and test stuff, it will be much easier not wait for cpu training.

If so, is there any changes that should be done to the deploy.prototxt, to the solver.prototxt or any other configuration file?

Thank you,
Gonçalo

**Comment by martinkersner** [comment]
Hi @charterscruz!

Training semantic segmentation can be performed using fcn8, but I am not sure if 4 GB are sufficient because CRF-RNN is built upon fcn network.

Anyway if you want to give a try, here are scripts for training [fcn32](https://gist.github.com/shelhamer/80667189b218ad570e82). Data preparation is the same as described in this repository.

Martin

**Comment by charterscruz** [comment]
@martinkersner I guess that you are right.
The models are approximately the same size, so it makes no difference regarding the GPU memory issues. I have tested and it also runs out of memory.

Maybe with [fcn-alex](https://gist.github.com/shelhamer/3f2c75f3c8c71357f24c) 4 GB is enough.
I am trying out this network but I am getting some syntax errors (I guess).
First, while parsing the *.prototxt it crashes with **layer{...** (by comparing with **TVG_CRFRNN_COCO_VOC.prototxt**, I have changed to **layers{...**
Then, the same happens with DATA and  CONVOLUTION. 
Finally I get stuck with  **Expected ":", found "{"**, but now the differences between the two networks are too significant and cannot figure out what should I change.

I believe this is caused by different flavors of caffe ([future](https://github.com/longjon/caffe/tree/future) and [crfasrnn](https://github.com/torrvision/crfasrnn)) Do you guys have any insight on this?

Thanks for the help.

Cheers

**Comment by martinkersner** [comment]
@charterscruz The easiest way to train model of CRF-RNN is to employ their provided [caffe](https://github.com/torrvision/crfasrnn) version, otherwise you would have to include to caffe couple of layers and rewrite prototxt. The problem you have with parsing *.prototxt* is caused by difference between old and new format.
