### ISSUE TITLE
typo in crfasrnn.py

### ISSUE THREAD

**Issue by HHH666** [martinkersner/train-CRF-RNN#6]
The code works like a charm.
However the default image lists from Ln38-41 should be ended with jpg not png.

BTW, if I want to add one layer or make some new functions to the 'MULTI_STAGE_MEANFIELD', could you please give me some advice on that. 
So far I'm only running the training and testing, but I have no idea where to start if I want to write my own layers.

Thanks!

**Comment by martinkersner** [comment]
I am glad you like it. Different extensions (*png* vs *jpg*) are caused by a slightly different dataset which I am using, but thanks for pointing out. 

Regarding to modifications of CRF-RNN you should better ask in [original repository](https://github.com/torrvision/crfasrnn) and for adding new layers you should check out [caffe users group](https://groups.google.com/forum/#!forum/caffe-users).
